// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znsliczpocigvwxsvtbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpuc2xpY3pwb2NpZ3Z3eHN2dGJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMjkyNDksImV4cCI6MjA2MTkwNTI0OX0.je0ZdToqSY-omLNRcfMuNTShtYx32CI4ftaxiwtJiCg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);